name: quality_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  get: ^3.24.0
  flutter_screenutil: ^4.0.3+2
  flash: ^1.3.2
  flutter_native_splash: ^0.2.9
  get_storage: ^1.4.0
  lottie: ^0.7.0+1
  intl_phone_number_input: ^0.6.0
  sms_autofill: ^1.3.1
  material_design_icons_flutter: 4.0.5855
  custom_navigation_bar: ^0.7.1
  connectivity: ^2.0.2
  dio: ^3.0.10
  flutter_staggered_grid_view: ^0.3.4
  flutter_datetime_picker: ^1.5.0
  http: ^0.12.2

flutter_native_splash:
  color: ffffff  # required parameter
  fill: true
  image: assets/images/launch_screen.png  # optional parameter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    #    - assets/lottie_icons/

  fonts:
    - family: CeraPro
      fonts:
        - asset: fonts/cera_pro/CeraPro-Regular.ttf
        - asset: fonts/cera_pro/CeraPro-Light.ttf
          weight: 300
        - asset: fonts/cera_pro/CeraPro-Medium.ttf
          weight: 500
        - asset: fonts/cera_pro/CeraPro-Medium.ttf
          weight: 600
        - asset: fonts/cera_pro/CeraPro-Bold.ttf
          weight: 700
        - asset: fonts/cera_pro/CeraPro-Black.ttf
          weight: 800
